### PR TITLE
Inline css style generation for modals

### LINKED ISSUE #57: Modals don't work without overriding styles
Modals are display: none, thanks to the bootstrap css. The om-bootstrap documentation uses a special asset that overrides this in http://om-bootstrap.herokuapp.com/static/assets/style.css

```
.bs-example .modal {
  position: relative;
  top: auto;
  right: auto;
  left: auto;
  bottom: auto;
  z-index: 1;
  display: block;
}
```

Should this be mentioned in the documentation? It might be worth providing a css file with om bootstrap that provides the correct behaviour?

Thanks

### PR DESCRIPTION
**Pull request by lenaschoenburg**
Opened in a hurry, I hope this PR works.

This should theoretically fix #57 but currently it breaks animation of modals flying in and out.

### CODE REVIEW

**Comment by lbradstreet** [comment]
Partially looks good. I tried it out and the modal is at least visible, however it shouldn't be position: relative. I have just realised that this is only used in the documentation so that it shows up inline in the docs (i.e. not as a modal). After I remove :position "relative", it all looks good.

**Comment by lbradstreet** [comment]
Hi @dignati, would you like me to fix this one? I think you just need to remove :position "relative" completely.

**Comment by dignati** [comment]
@lbradstreet  Sorry, I'm in my finals right now so I totally forgot about this. This should do the trick.
@sritchie Ready to merge?

**Comment by lbradstreet** [comment]
No worries, and thanks!

**Pull request closed without merging**
