### PR TITLE
make Om a provided dependency

### PR DESCRIPTION
**Pull request by sritchie**
Since David added `org.om` as a prefix, the two versions of Om clash with each other.

### CODE REVIEW

**Comment by dignati** [comment]
Shouldn't that be org.omcljs/om? https://github.com/swannodette/om/blob/master/project.clj

**Comment by sritchie** [comment]
@dignati, @swannodette did a couple of package changes. First he added `org.om` , then changed it to `org.omcljs`. Changing the scope of this dep to provided means you can include whichever version you want. When I upgrade om-bootstrap to support the new Om I'll mention that in the docs.

**Comment by sritchie** [comment]
org.om: https://github.com/swannodette/om/commit/1c5e9eb1a44562be3f5936c6492dae7f624995f7
org.omcljs: https://github.com/swannodette/om/commit/614b0a02d679899567ebb75b65445aff8625925f

**Comment by dignati** [comment]
That's right, although 0.8.0 -> 0.8.6 only contains bug-fixes and dependency bumps. Might be worth it to skip right to 0.8.6?

**Comment by sritchie** [comment]
Yeah, I'll keep the dep provided so that users can do whichever one they want. As long as Om sticks to Semantic versioning all should be well.

**Pull request merged**
